import type { Locale } from "@/lib/i18n/messages";

const sv = {
  county: "Län", municipality: "Kommun", district: "Valdistrikt", country: "Hela Sverige", counties: "Län", municipalities: "Kommuner", districts: "Valdistrikt",
  chooseCounty: "Välj län", chooseMunicipality: "Välj kommun", allMunicipalities: "Alla kommuner", countyOverview: "Hela länet", municipalityOverview: "Hela kommunen",
  party: "Parti", other: "Övriga partier", year: "Valår", metric: "Kartans mått", share: "Röstandel", swing: "Förändring 2018–2022", turnout: "Valdeltagande", votes: "Röster", validVotes: "Giltiga röster", totalVotes: "Samtliga röster", eligible: "Röstberättigade", pp: "procentenheter",
  official: "Officiella röster · Riksdagsval", derived: "Beräknat från officiella röster", history: "Partiets historia", historyNote: "Kommun- och länshistorik visar resultat i respektive års administrativa indelning. Distriktshistorik visas bara med en verifierad jämförelse.",
  area: "Område", open: "Öppna", selectParty: "Välj parti", list: "Utforska områden", search: "Sök i områdeslistan", sort: "Sortera områden", alphabetical: "Namn A–Ö", strongest: "Högst värde först", weakest: "Lägst värde först", noMatches: "Inga områden matchar sökningen.",
  comparisonMissing: "Ingen säker jämförelse med 2018. Ändrad indelning redovisas som saknad historik, aldrig som noll röster.", sharedBaseline: "Två distrikt pekar på samma referens från 2018. Förändringen visas inte för att undvika en missvisande jämförelse.", comparison: "Jämförbara distrikt 2018", combined: "Sammanlagda röster i referensdistrikten", unavailable: "Resultat saknas för det valåret på denna nivå.", availability: "Län och kommuner: 2010–2022. Valdistrikt: 2022, samt jämförbara resultat från 2018.",
  collection: "Uppsamlingsdistrikt", collectionNote: "Sena förtidsröster och utlandsröster som inte nått vallokalen i tid redovisas här samlat för kommunen. De ingår i kommunens och länets resultat, men har ingen egen kartyta eller separat röstlängd. Lokalt valdeltagande kan därför inte beräknas för dem.",
  parentDifference: "Skillnad mot", national: "Riket", allParties: "Alla partier i området", noResult: "Ingen uppgift", loading: "Hämtar valdistrikt…", error: "Valdistrikten kunde inte hämtas. Kommunens verifierade resultat finns kvar. Försök igen.", retry: "Försök igen", missingDistrict: "Det länkade valdistriktet finns inte i denna kommun. Kommunöversikten visas.",
  map: "Klickbar valkarta", mapHelp: "Klicka på ett område för att gå vidare. Samma områden finns i listan nedanför.", lower: "Lägre", higher: "Högre", missing: "Saknas / ej jämförbart", shareLink: "Kopiera länk till vyn", copied: "Länken är kopierad", copyFailed: "Kopiera adressen i webbläsaren för att dela vyn.",
  source: "Källor och beräkning", sourceLink: "Valmyndighetens rådata och jämförelsenyckel", method: "Röstandel = partiets röster / giltiga röster. Valdeltagande = samtliga röster / röstberättigade. Län summeras från kommunernas röstetal; procenttal medelvärdesbildas inte. Förändring och skillnad mot överordnat område anges i procentenheter och beräknas före avrundning. Visade andelar avrundas till två decimaler.", geometry: "Godkända utlandsröster ingår i slutresultaten. Uppsamlingsröster fördelas inte tillbaka på enskilda kartdistrikt. Kartans indelning: 2022. Län är administrativa län, inte riksdagens valkretsar. Övriga partier är en samlad kategori.",
  live: "2026 års rösträkning", liveNote: "Detta är slutliga historiska resultat. Följ nya 2026-siffror i valnattsvyn.", readData: "Ladda ner områdets data", inspected: "Källor hämtade", count: "områden", noTurnout: "Ingen separat röstlängd", historicalElection: "Riksdagsvalets geografiska resultat. Kommunfullmäktige är ett separat val.",
};
const en: Record<keyof typeof sv, string> = {
  county: "County", municipality: "Municipality", district: "Electoral district", country: "All of Sweden", counties: "Counties", municipalities: "Municipalities", districts: "Electoral districts",
  chooseCounty: "Choose county", chooseMunicipality: "Choose municipality", allMunicipalities: "All municipalities", countyOverview: "Whole county", municipalityOverview: "Whole municipality",
  party: "Party", other: "Other parties", year: "Election year", metric: "Map metric", share: "Vote share", swing: "Change 2018–2022", turnout: "Turnout", votes: "Votes", validVotes: "Valid votes", totalVotes: "All ballots", eligible: "Eligible voters", pp: "percentage points",
  official: "Official votes · Riksdag election", derived: "Calculated from official votes", history: "Party history", historyNote: "Municipal and county history uses the administrative areas of each election year. District history requires a verified comparison.",
  area: "Area", open: "Open", selectParty: "Choose party", list: "Explore areas", search: "Search the area list", sort: "Sort areas", alphabetical: "Name A–Z", strongest: "Highest value first", weakest: "Lowest value first", noMatches: "No areas match your search.",
  comparisonMissing: "No reliable comparison with 2018. Changed boundaries are shown as missing history, never as zero votes.", sharedBaseline: "Two districts reference the same 2018 district. Change is withheld to avoid a misleading comparison.", comparison: "Comparable districts in 2018", combined: "Combined votes in the reference districts", unavailable: "Results for that election year are unavailable at this level.", availability: "Counties and municipalities: 2010–2022. Districts: 2022 and comparable 2018 results.",
  collection: "Collection districts", collectionNote: "Late advance votes and overseas votes that did not reach polling stations in time are grouped here for the municipality. They contribute to municipal and county results but have no separate map area or electorate. Their local turnout therefore cannot be calculated.",
  parentDifference: "Difference from", national: "Sweden", allParties: "All parties in this area", noResult: "Unavailable", loading: "Loading electoral districts…", error: "District data could not be loaded. The verified municipal results are still available. Please try again.", retry: "Try again", missingDistrict: "The linked district does not exist in this municipality. Showing the municipal overview.",
  map: "Interactive election map", mapHelp: "Select an area to explore it. The same areas are available in the list below.", lower: "Lower", higher: "Higher", missing: "Missing / not comparable", shareLink: "Copy link to this view", copied: "Link copied", copyFailed: "Copy the browser address to share this view.",
  source: "Sources and calculation", sourceLink: "Valmyndigheten raw data and comparison key", method: "Vote share = party votes / valid votes. Turnout = all ballots / eligible voters. County totals sum municipal vote counts; percentages are never averaged. Changes and differences from the parent area are calculated before rounding and expressed in percentage points. Displayed shares are rounded to two decimals.", geometry: "Accepted overseas votes are included in the final results. Collection votes are not redistributed to individual map districts. Map boundaries: 2022. Counties are administrative counties, not Riksdag constituencies. Other parties are a combined category.",
  live: "2026 vote count", liveNote: "These are final historical results. Follow new 2026 figures in the election-night view.", readData: "Download area data", inspected: "Sources retrieved", count: "areas", noTurnout: "No separate electorate", historicalElection: "Geographic results of the Riksdag election. Municipal council elections are separate.",
};
export function localCopy(locale: Locale) { return locale === "en" ? en : sv; }
export type LocalCopy = typeof sv;
