import { pageMetadata } from "@/lib/page-metadata";
import type { Locale } from "@/lib/i18n/messages";
export const metadata = { ...pageMetadata("privacy", "sv"), title: "Integritet och statistik" };
export default function PrivacyPage({ locale = "sv" }: {
    locale?: Locale;
} = {}) {
    const sv = locale === "sv";
    return <section className="product-section" style={{ maxWidth: 900, marginInline: "auto" }}><p className="eyebrow">Politicalverse</p><h1>{sv ? "Integritet och statistik" : "Privacy and statistics"}</h1><p>{sv ? "Senast uppdaterad 11 september 2026. Politicalverse drivs av William Rydh. Kontakta oss på vladde86@gmail.com om du har frågor om dina uppgifter eller vill utöva dina rättigheter." : "Updated 11 September 2026. Politicalverse is operated by William Rydh. Contact vladde86@gmail.com about your data or to exercise your rights."}</p>
 <h2>{sv ? "Ditt val" : "Your choice"}</h2><p>{sv ? "Du kan använda sajten utan besöksstatistik. Mätningen startar först när du klickar på Godkänn. Vi spelar inte in skärmen och använder inte statistiken för annonser." : "You can use the site without visitor analytics. Measurement starts only after you click Accept. We do not record your screen or use analytics for advertising."}</p>
 <h2>{sv ? "Vad vi mäter" : "What we measure"}</h2><p>{sv ? "Vår egen statistik räknar sidvisningar, kortvariga besök med slumpmässig nyckel, steg mellan sidor, trafikkällans domänkategori, utvalda lanseringskampanjer, språk, enhetstyp, webbläsare, operativsystem, fönster- och skärmstorlek, aktiv tid samt tekniska prestandamått och feltyper. Funktioner som sök, filter, sortering och länkar till PocketPolitics och officiella källor räknas utan inmatad text." : "Our own analytics counts page views, short-lived visits with a random key, navigation steps, referring-domain categories, selected launch campaigns, language, device type, browser, operating system, window and screen dimensions, active time, performance metrics and error categories. Use of search, filters, sorting and links to PocketPolitics and official sources is counted without entered text."}</p><p>{sv ? "Vi sparar inte namn, IP-adresser i besöksstatistiken, sökfraser, formulärinnehåll, kandidatval eller partival. Adresser rensas från sökparametrar. Besöksnyckeln är slumpmässig och hör till en flik, med förnyelse efter 30 minuters inaktivitet. Den används inte för att känna igen dig mellan olika besök eller sajter." : "We do not store names, IP addresses in visitor statistics, search phrases, form contents, candidate selections or party selections. Query parameters are removed from addresses. The visit key is random and tab-scoped, renewed after 30 minutes of inactivity. It is not used to recognise you across visits or sites."}</p>
 <h2>{sv ? "Lagring och leverantörer" : "Storage and providers"}</h2><p>{sv ? "Besöksstatistiken lagras i Cloudflare D1 med EU-jurisdiktion och raderas dagligen när de är äldre än 90 dagar. Cloudflare behandlar nätverksuppgifter för drift och säkerhet; vår server använder en kortlivad nycklad hash för att begränsa missbruk. Samtyckesvalet sparas i din webbläsare i 180 dagar. Språk- och temainställningar är funktionella inställningar, skilda från statistiken." : "Visitor analytics is stored in Cloudflare D1 with EU jurisdiction and deleted daily once it is older than 90 days. Cloudflare processes network information for operation and security; our server uses a short-lived keyed hash to limit abuse. Your consent choice is saved in your browser for 180 days. Language and theme preferences are functional settings, separate from analytics."}</p><p>{sv ? "Google Analytics är inte aktiverat. Ingen statistik skickas till Google." : "Google Analytics is not enabled. No analytics is sent to Google."}</p><p>{sv ? "Statistikvalet lagras som pv-statistics-v1 i localStorage i 180 dagar. Efter tillåtelse sparas pv-visit-v1 och pv-last-route-v1 i flikens sessionStorage tills fliken stängs; besöksnyckeln förnyas efter 30 minuters inaktivitet. Admininloggning använder den nödvändiga sessionskakan __Host-pv_admin i högst åtta timmar. Den används inte för besöksmätning." : "The statistics choice is stored as pv-statistics-v1 in localStorage for 180 days. After permission, pv-visit-v1 and pv-last-route-v1 are stored in the tab's sessionStorage until the tab closes; the visit key is renewed after 30 minutes of inactivity. Admin login uses the essential __Host-pv_admin session cookie for up to eight hours. It is not used for visitor analytics."}</p><p><a href="https://www.cloudflare.com/privacypolicy/" target="_blank" rel="noopener noreferrer">{sv ? "Cloudflares integritetspolicy" : "Cloudflare privacy policy"}</a></p>
 <h2>{sv ? "Dina rättigheter" : "Your rights"}</h2><p>{sv ? "Du kan begära information, rättelse eller radering och återkalla ditt samtycke. Eftersom vi inte identifierar besökare kan vi behöva mer information för att hitta just dina uppgifter. Du kan lämna klagomål till Integritetsskyddsmyndigheten, IMY." : "You can request information, correction or erasure and withdraw consent. Because we do not identify visitors, we may need additional information to locate your records. You can complain to the Swedish Authority for Privacy Protection, IMY."} <a href="https://www.imy.se/" target="_blank" rel="noopener noreferrer">IMY</a>.</p></section>;
}
