/* Served only after server-side authentication. All API data becomes text nodes. */
const $=id=>document.getElementById(id);
const number=value=>Number(value??0).toLocaleString('sv-SE');
const name={mobile:'Mobil',tablet:'Surfplatta',desktop:'Dator',other:'Övrigt',unknown:'Okänd',direct:'Direkt / okänd',browser:'Webbläsare',pwa:'Hemskärmsapp',page:'Sidvisning',pocketpolitics:'Till PocketPolitics',source_open:'Öppnad källa',filter_change:'Ändrat filter',table_sort:'Sorterat tabell',search:'Använt sök',scroll:'Läsdjup',script_error:'Skriptfel',resource_error:'Resursfel'};
let currentReport=null,reportSequence=0,reportLoading=false;
const text=(id,value)=>{$(id).textContent=value;};
const empty=(id,message='Ingen statistik ännu för den här perioden.')=>{const p=document.createElement('p');p.className='empty';p.textContent=message;$(id).replaceChildren(p);};
async function api(path){const r=await fetch(path,{cache:'no-store',signal:AbortSignal.timeout(10000)});if(r.status===401){location.assign('/admin/');throw new Error('Inloggningen har gått ut.');}if(!r.ok)throw new Error('Statistiken kunde inte hämtas. Försök igen.');return r.json();}
function table(id,columns,rows){
 if(!rows?.length){empty(id);return;}
 const wrap=document.createElement('div');wrap.className='table-wrap';const t=document.createElement('table'),head=document.createElement('thead'),tr=document.createElement('tr'),body=document.createElement('tbody');let sort=null,asc=false;
 const render=()=>{body.replaceChildren();const ordered=[...rows];if(sort)ordered.sort((a,b)=>{const av=a[sort],bv=b[sort];return (typeof av==='number'&&typeof bv==='number'?av-bv:String(av??'').localeCompare(String(bv??''),'sv'))*(asc?1:-1);});for(const row of ordered){const line=document.createElement('tr');for(const c of columns){const cell=document.createElement('td'),v=row[c.key];if(c.path && typeof v==='string' && /^\/(en\/)?[a-z0-9/-]*$/.test(v)){const a=document.createElement('a');a.href=v;a.target='_blank';a.rel='noopener';a.textContent=v;cell.append(a);}else cell.textContent=c.format?c.format(v,row):typeof v==='number'?number(v):(name[v]??v??'—');line.append(cell);}body.append(line);}};
 for(const c of columns){const th=document.createElement('th');th.scope='col';const b=document.createElement('button');b.textContent=c.label+' ↕';b.addEventListener('click',()=>{asc=sort===c.key?!asc:typeof rows[0][c.key]!=='number';sort=c.key;for(const h of tr.children)h.removeAttribute('aria-sort');th.setAttribute('aria-sort',asc?'ascending':'descending');render();});th.append(b);tr.append(th);}head.append(tr);t.append(head,body);wrap.append(t);$(id).replaceChildren(wrap);render();
}
function timeline(rows){
 if(!rows.length){empty('timeline','När de första besöken kommer visas utvecklingen här.');return;}
 const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('viewBox','0 0 900 230');svg.setAttribute('class','chart');svg.setAttribute('role','img');svg.setAttribute('aria-label','Dagliga sidvisningar och besök. Exakta värden finns i CSV-exporten.');const max=Math.max(...rows.map(r=>r.pageviews),1);const add=(tag,attrs)=>{const el=document.createElementNS(svg.namespaceURI,tag);Object.entries(attrs).forEach(([k,v])=>el.setAttribute(k,String(v)));svg.append(el);return el;};
 for(let i=0;i<4;i++){const y=15+i*60;add('line',{x1:45,x2:885,y1:y,y2:y,stroke:'#2c404e'});const label=add('text',{x:0,y:y+4,fill:'#a4b7c4','font-size':12});label.textContent=number(Math.round(max*(1-i/3)));}
 for(const [key,color]of[['pageviews','#9dccdf'],['visits','#b7b2df']]){const points=rows.map((r,i)=>[45+(rows.length===1?420:i/(rows.length-1)*840),195-(r[key]/max)*180]);add('polyline',{points:points.map(p=>p.join(',')).join(' '),fill:'none',stroke:color,'stroke-width':2.5,'stroke-linecap':'round','stroke-linejoin':'round'});points.forEach((p,i)=>{const dot=add('circle',{cx:p[0],cy:p[1],r:3,fill:color});const title=document.createElementNS(svg.namespaceURI,'title');title.textContent=rows[i].day+': '+number(rows[i][key])+' '+(key==='visits'?'besök':'sidvisningar');dot.append(title);});}
 const labels=document.createElement('div');labels.className='chart-labels';for(const row of[rows[0],rows.at(-1)]){const span=document.createElement('span');span.textContent=row.day;labels.append(span);} $('timeline').replaceChildren(svg,labels);
}
function comparison(value,old,complete){if(!complete||!old)return 'Jämförbart tidigare underlag saknas';const change=(value-old)/old*100;return (change>0?'+':'')+change.toLocaleString('sv-SE',{maximumFractionDigits:1})+' % mot föregående period';}
function renderReport(r){
 const totals=r.totals[0]??{},prior=r.previous[0]??{},engagement=r.engagement[0]??{},first=r.collection[0]?.since;
 const complete=first&&first<=Date.parse(r.windowStart)/1000-r.days*86400;
 text('visits',number(totals.visits));text('views',number(totals.pageviews));text('visit-change',comparison(totals.visits,prior.visits,complete));text('view-change',comparison(totals.pageviews,prior.pageviews,complete));
 const seconds=engagement.visits?Math.round(engagement.engaged_ms/engagement.visits/1000):null;text('engaged',seconds===null?'—':Math.floor(seconds/60)+'m '+seconds%60+'s');
 const daily=new Map(r.daily.map(row=>[row.day,row]));
 const firstDay=first?new Date(Math.max(first*1000,Date.parse(r.windowStart))).toLocaleDateString("sv-SE",{timeZone:"Europe/Stockholm"}):null;
 const lastDay=new Date(r.generatedAt).toLocaleDateString("sv-SE",{timeZone:"Europe/Stockholm"});
 const filled=[];if(firstDay)for(let day=firstDay;day<=lastDay;day=new Date(Date.parse(day)+86400000).toISOString().slice(0,10))filled.push(daily.get(day)??{day,pageviews:0,visits:0});
 timeline(filled);text('collection-start',first?'Äldsta sparade besök: '+new Date(first*1000).toLocaleString('sv-SE',{timeZone:'Europe/Stockholm'}):'Mätningen är redo. Inga besök har registrerats ännu.');
 table('pages',[{key:'path',label:'Sida',path:true},{key:'visits',label:'Besök'},{key:'pageviews',label:'Visningar'}],r.pages);
 table('transitions',[{key:'previous_path',label:'Från',path:true},{key:'path',label:'Till',path:true},{key:'transitions',label:'Steg'}],r.transitions);
 for(const id of['entries','exits'])table(id,[{key:'path',label:'Sida',path:true},{key:'visits',label:'Besök'}],r[id]);
 table('sources',[{key:'source',label:'Källa'},{key:'campaign',label:'Kampanj'},{key:'visits',label:'Besök'}],r.sources);
 table('devices',[{key:'device',label:'Enhet'},{key:'browser',label:'Webbläsare'},{key:'os',label:'System'},{key:'mode',label:'Läge'},{key:'visits',label:'Besök'}],r.devices);
 table('screens',[{key:'viewport',label:'Fönster'},{key:'screen',label:'Skärm'},{key:'visits',label:'Besök'}],r.screens);
 table('events',[{key:'kind',label:'Händelse'},{key:'path',label:'Sida',path:true},{key:'label',label:'Detalj'},{key:'visits',label:'Besök'},{key:'events',label:'Antal'}],r.events);
 const groups=new Map();for(const s of r.performanceSamples){const key=s.kind+' '+s.path;if(!groups.has(key))groups.set(key,{kind:s.kind,path:s.path,values:[]});groups.get(key).values.push(s.value);}
 const performance=[...groups.values()].map(g=>{g.values.sort((a,b)=>a-b);return{kind:g.kind,path:g.path,samples:g.values.length,p75:g.values[Math.ceil(g.values.length*.75)-1]};});
 table('performance',[{key:'kind',label:'Mått'},{key:'path',label:'Sida',path:true},{key:'samples',label:'Mätningar'},{key:'p75',label:'p75',format:(v,row)=>Number(v).toLocaleString('sv-SE',{maximumFractionDigits:3})+(row.kind==='CLS'?'':' ms')}],performance);
 text('report-status','Uppdaterad '+new Date(r.generatedAt).toLocaleTimeString('sv-SE')+' · Rullande period, dygn grupperade i svensk tid.');$('report-status').className='status';$('export').disabled=false;
}
async function loadReport(force=false){if(reportLoading&&!force)return;reportLoading=true;const sequence=++reportSequence;const days=$('days').value;text('report-status','Hämtar statistik …');try{const report=await api('/admin/api/report?days='+days);if(sequence!==reportSequence)return;currentReport=report;renderReport(report);}catch(e){if(sequence!==reportSequence)return;text('report-status',e.message);$('report-status').className='status error';}finally{if(sequence===reportSequence)reportLoading=false;}}
let liveLoading=false;
async function loadLive(){if(liveLoading||document.hidden)return;liveLoading=true;try{const r=await api('/admin/api/realtime');text('active',number(r.pages.reduce((a,p)=>a+p.visitors,0)));text('live-time',new Date(r.generatedAt).toLocaleTimeString('sv-SE'));table('live-pages',[{key:'path',label:'Adress',path:true},{key:'visitors',label:'Aktiva besök'}],r.pages);table('live-devices',[{key:'device',label:'Enhet'},{key:'visitors',label:'Aktiva besök'}],r.devices);text('last30','Senaste 30 minuterna: '+number(r.last30Minutes?.visitors)+' besök');}catch{text('active','—');text('live-time','Uppdatering misslyckades – försöker igen.');}finally{liveLoading=false;}}
async function loadSystem(){try{const r=await api('/admin/api/system');table('system',[{key:'path',label:'Resurs',path:true},{key:'status',label:'HTTP',format:v=>v??'Ej tillgänglig'},{key:'ms',label:'ms'}],r.checks);text('system-status','Kontrollerad '+new Date(r.checkedAt).toLocaleTimeString('sv-SE'));text('ga-status',r.analytics.measurementId?'Google Analytics: '+r.analytics.measurementId+' är konfigurerat. Datamottagning verifieras i Google.':'Google Analytics väntar på kontoanslutning. Den egna statistiken fungerar separat.');}catch{text('system-status','Tillgänglighetskontrollen kunde inte slutföras.');}}
$('days').addEventListener('change',()=>{currentReport=null;$('export').disabled=true;for(const id of['visits','views','engaged'])text(id,'—');for(const id of['timeline','pages','transitions','entries','exits','sources','devices','screens','events','performance'])empty(id,'Hämtar vald period …');text('visit-change','');text('view-change','');void loadReport(true);});$('refresh').addEventListener('click',()=>{void loadReport(true);void loadLive();void loadSystem();});
$('export').addEventListener('click',()=>{if(!currentReport)return;const sections=['daily','pages','transitions','entries','exits','sources','devices','screens','events','performanceSamples'];const fields=[...new Set(sections.flatMap(section=>currentReport[section].flatMap(row=>Object.keys(row))))];const lines=[['section',...fields]];for(const section of sections)for(const row of currentReport[section])lines.push([section,...fields.map(field=>row[field]??'')]);const csv='\uFEFF'+lines.map(row=>row.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(';')).join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='politicalverse-insikter-'+new Date().toISOString().slice(0,10)+'.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
void loadReport();void loadLive();void loadSystem();setInterval(()=>{void loadLive();},10000);setInterval(()=>{if(!document.hidden)void loadReport();},60000);document.addEventListener('visibilitychange',()=>{if(!document.hidden){void loadLive();void loadReport();}});
